#include "en675.h"
#include "reg.h"

#define SFLS_BUS_CMD_T _am(_SFLS_1,REG_BASE_SFLS, (1<<3))
#define SFLS_BUS_MODE_T _am(_SFLS_2,REG_BASE_SFLS, (2<<3))
#define SFLS_USR_T _am(_SFLS_3,REG_BASE_SFLS, (3<<3))

void sfls_init()
{
	while(!SFLS_ID_VAL);
	SFLS_BUS_CMD_T = 0xEB020605;
	SFLS_BUS_MODE_T = 0xAAAA9500;
#if 0
	SFLS_BUS_CMD_RD		= 0xEB;
	SFLS_BUS_CMD_WR		= 0x02;
	SFLS_BUS_CMD_WREN	= 0x06;
	SFLS_BUS_CMD_RDREG	= 0x05;
	SFLS_BUS_RD_CMD_MODE = 2;
	SFLS_BUS_RD_ADR_MODE = 2;
	SFLS_BUS_RD_DAT_MODE = 2;
	SFLS_BUS_WR_CMD_MODE = 2;
	SFLS_BUS_WR_ADR_MODE = 2;
	SFLS_BUS_WR_DAT_MODE = 2;
	SFLS_BUS_WREN_CMD_MODE = 2;
	SFLS_BUS_RDREG_CMD_MODE = 2;
	SFLS_BUS_RDREG_DAT_MODE = 2;
	SFLS_BUS_GAP_EN = 1;
	SFLS_BUS_GAP = 5;
#endif
	SFLS_USR_CMD = 0x35;
	SFLS_IO_RDLTC = 2;
	SFLS_USRBUS_REQ = 1;
	while(SFLS_USRBUS_REQ);
}

